# Generated by Django 4.2.5 on 2023-10-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_alter_users_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.CharField(max_length=100)),
                ("item_price", models.IntegerField()),
                ("item_bid", models.IntegerField()),
                ("image1", models.ImageField(upload_to="images/")),
                ("image2", models.ImageField(upload_to="images/")),
                ("image3", models.ImageField(upload_to="images/")),
                ("image4", models.ImageField(upload_to="images/")),
                ("image5", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apartment_name", models.CharField(max_length=100)),
                ("price_daily", models.IntegerField()),
                ("price_weekly", models.IntegerField()),
                ("price_monthly", models.IntegerField()),
                ("location", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("image1", models.ImageField(upload_to="images/")),
                ("image2", models.ImageField(upload_to="images/")),
                ("image3", models.ImageField(upload_to="images/")),
                ("image4", models.ImageField(upload_to="images/")),
                ("image5", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
