# Generated by Django 4.2.5 on 2023-10-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_auction_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="duration",
            field=models.CharField(max_length=50),
        ),
    ]
