# Generated by Django 4.2.5 on 2023-10-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_auctioned_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image1",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image2",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image3",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image4",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="image5",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="auction",
            name="item_bid",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="item_description",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="item_price",
            field=models.IntegerField(null=True),
        ),
    ]
