# Generated by Django 4.2.5 on 2023-11-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_auction_image1_alter_auction_image2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("content", models.TextField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("contact", models.CharField(max_length=100)),
                ("image1", models.ImageField(upload_to="images/")),
                ("image2", models.ImageField(upload_to="images/")),
                ("image3", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
