# Generated by Django 4.2.5 on 2023-11-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_apartment"),
    ]

    operations = [
        migrations.CreateModel(
            name="services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=800)),
                ("price", models.CharField(max_length=800)),
                ("requirement", models.CharField(max_length=8000)),
                ("contact", models.CharField(max_length=800)),
                ("email", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=800)),
                ("state", models.CharField(max_length=800)),
                ("image1", models.ImageField(null=True, upload_to="images/")),
                ("image2", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
        migrations.AlterField(
            model_name="apartment",
            name="address",
            field=models.CharField(max_length=500, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="contact",
            field=models.CharField(max_length=100, verbose_name="Contact Information"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="content",
            field=models.TextField(max_length=500, verbose_name="Description of room"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="duration",
            field=models.CharField(max_length=50, verbose_name="Length of stay"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="image1",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Room"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="image2",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Room"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="image3",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Room"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.IntegerField(verbose_name="Price for room"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="image1",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Item"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="image2",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Item"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="image3",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Item"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="image4",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Item"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="image5",
            field=models.ImageField(upload_to="images/", verbose_name="Image of Item"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="item_bid",
            field=models.IntegerField(verbose_name="Your starting bid price"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="item_description",
            field=models.CharField(max_length=100, verbose_name="Description of Item"),
        ),
        migrations.AlterField(
            model_name="auctioned_item",
            name="item_price",
            field=models.IntegerField(verbose_name="Price of Item"),
        ),
    ]
