# Generated by Django 4.2.5 on 2023-11-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_services_alter_apartment_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="address",
            field=models.CharField(max_length=800, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="services",
            name="contact",
            field=models.CharField(max_length=800, verbose_name="Phone no +234"),
        ),
        migrations.AlterField(
            model_name="services",
            name="email",
            field=models.CharField(max_length=50, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="services",
            name="price",
            field=models.CharField(max_length=800, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="services",
            name="requirement",
            field=models.TextField(max_length=8000, verbose_name="Requirements"),
        ),
        migrations.AlterField(
            model_name="services",
            name="state",
            field=models.CharField(max_length=800, verbose_name="State"),
        ),
        migrations.AlterField(
            model_name="services",
            name="title",
            field=models.CharField(max_length=800, verbose_name="Description of job"),
        ),
    ]
