# Generated by Django 4.2.5 on 2023-11-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_alter_services_address_alter_services_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="image1",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Document Image"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="image2",
            field=models.ImageField(
                null=True, upload_to="images/", verbose_name="Document Image"
            ),
        ),
    ]
