# Generated by Django 4.2.5 on 2023-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_alter_services_image1_alter_services_image2"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=900, verbose_name="Username")),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "title",
                    models.CharField(max_length=900, verbose_name="Title of blog"),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=8000, verbose_name="Write your content"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Document Image"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        null=True, upload_to="images/", verbose_name="Document Image"
                    ),
                ),
            ],
        ),
    ]
