# Generated by Django 4.2.5 on 2023-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=800, verbose_name="FirstName"),
                ),
                (
                    "lastname",
                    models.TextField(max_length=8000, verbose_name="LastName"),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="PhoneNo")),
                (
                    "passport",
                    models.ImageField(
                        null=True,
                        upload_to="images/",
                        verbose_name="Upload Passport Photograph ",
                    ),
                ),
                (
                    "speciality",
                    models.CharField(max_length=800, verbose_name="Area of Specialty"),
                ),
                (
                    "description",
                    models.TextField(max_length=800, verbose_name="Describe your Work"),
                ),
                (
                    "job",
                    models.CharField(max_length=800, verbose_name="Current Profession"),
                ),
                (
                    "price",
                    models.IntegerField(max_length=800, verbose_name="Price per Job"),
                ),
                ("state", models.CharField(max_length=800, verbose_name="State")),
                ("address", models.CharField(max_length=800, verbose_name="Address")),
            ],
        ),
    ]
