# Generated by Django 4.2.5 on 2023-11-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="username",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
