# Generated by Django 4.2.5 on 2023-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_worker_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="description",
            field=models.TextField(verbose_name="Describe your Work"),
        ),
    ]
