# Generated by Django 4.2.5 on 2023-11-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_alter_worker_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="lastname",
            field=models.CharField(max_length=8000, verbose_name="LastName"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone",
            field=models.IntegerField(verbose_name="PhoneNo"),
        ),
        migrations.AlterField(
            model_name="worker",
            name="price",
            field=models.IntegerField(verbose_name="Price per Job"),
        ),
    ]
