# Generated by Django 4.2.5 on 2023-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0026_alter_worker_lastname_alter_worker_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="local_govt",
            field=models.CharField(max_length=80, null=True, verbose_name="Local Govt"),
        ),
        migrations.AlterField(
            model_name="services",
            name="contact",
            field=models.CharField(max_length=80, verbose_name="Phone no +234"),
        ),
        migrations.AlterField(
            model_name="services",
            name="price",
            field=models.CharField(max_length=80, verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="services",
            name="state",
            field=models.CharField(max_length=80, verbose_name="State"),
        ),
    ]
