# Generated by Django 4.2.7 on 2023-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_remove_services_image1_remove_services_image2"),
    ]

    operations = [
        migrations.CreateModel(
            name="verifiedworker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=80, null=True)),
                (
                    "firstname",
                    models.CharField(max_length=800, verbose_name="FirstName"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=8000, verbose_name="LastName"),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("phone", models.IntegerField(verbose_name="PhoneNo")),
                (
                    "passport",
                    models.ImageField(
                        null=True,
                        upload_to="images/",
                        verbose_name="Upload Passport Photograph ",
                    ),
                ),
                (
                    "speciality",
                    models.CharField(max_length=800, verbose_name="Area of Specialty"),
                ),
                ("description", models.TextField(verbose_name="Describe your Work")),
                (
                    "job",
                    models.CharField(max_length=800, verbose_name="Current Profession"),
                ),
                ("price", models.IntegerField(verbose_name="Price per Job")),
                ("state", models.CharField(max_length=800, verbose_name="State")),
                ("address", models.CharField(max_length=800, verbose_name="Address")),
            ],
        ),
    ]
