# Generated by Django 4.2.7 on 2023-11-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_verifiedworker"),
    ]

    operations = [
        migrations.DeleteModel(
            name="verifiedworker",
        ),
    ]
