# Generated by Django 4.2.7 on 2023-11-25 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0031_verifiedworker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "random_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("username", models.CharField(max_length=80, null=True)),
                (
                    "firstname",
                    models.CharField(max_length=800, verbose_name="FirstName"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=8000, verbose_name="LastName"),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("phone", models.IntegerField(verbose_name="PhoneNo")),
                (
                    "passport",
                    models.ImageField(
                        null=True,
                        upload_to="images/",
                        verbose_name="Upload Passport Photograph ",
                    ),
                ),
                (
                    "speciality",
                    models.CharField(max_length=800, verbose_name="Area of Specialty"),
                ),
                ("description", models.TextField(verbose_name="Describe your Work")),
                (
                    "job",
                    models.CharField(max_length=800, verbose_name="Current Profession"),
                ),
                ("price", models.IntegerField(verbose_name="Price per Job")),
                ("state", models.CharField(max_length=800, verbose_name="State")),
                ("address", models.CharField(max_length=800, verbose_name="Address")),
            ],
        ),
    ]
