# Generated by Django 4.2.7 on 2023-11-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_workers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workers",
            name="random_id",
        ),
        migrations.AddField(
            model_name="worker",
            name="randoms",
            field=models.IntegerField(null=True),
        ),
    ]
