# Generated by Django 4.2.7 on 2023-11-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_services_randoms"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="username",
            field=models.CharField(max_length=80, null=True),
        ),
    ]
