# Generated by Django 4.2.7 on 2023-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_services_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workercontact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("randoms", models.IntegerField(null=True)),
                ("username", models.CharField(max_length=80, null=True)),
                ("description", models.TextField(verbose_name="State  your Request")),
                ("date", models.DateField()),
            ],
        ),
    ]
