# Generated by Django 4.2.7 on 2023-11-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_workercontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="workercontact",
            name="email",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Email for Contact"
            ),
        ),
    ]
