# Generated by Django 4.2.7 on 2023-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_workercontact_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passport",
                    models.ImageField(
                        null=True,
                        upload_to="images/",
                        verbose_name="Upload Passport Photograph ",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=800, verbose_name="FirstName"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=8000, verbose_name="LastName"),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("phone", models.IntegerField(verbose_name="PhoneNo")),
                (
                    "speciality",
                    models.CharField(
                        max_length=800, verbose_name="Area of Specialization"
                    ),
                ),
                ("description", models.TextField(verbose_name="Describe your Work")),
                ("job", models.CharField(max_length=800, verbose_name=" Profession")),
                ("price", models.IntegerField(verbose_name="Price")),
                ("state", models.CharField(max_length=800, verbose_name="State")),
                ("address", models.CharField(max_length=800, verbose_name="Address")),
                (
                    "files",
                    models.FileField(
                        null=True, upload_to="images/", verbose_name="Upload CV "
                    ),
                ),
            ],
        ),
    ]
