# Generated by Django 4.2.7 on 2023-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="responsible",
            field=models.TextField(
                max_length=8000, null=True, verbose_name="Responsibilities"
            ),
        ),
    ]
