# Generated by Django 4.2.7 on 2023-11-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_services_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
