# Generated by Django 4.2.7 on 2023-11-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0040_worker_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="verified",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
