# Generated by Django 4.2.7 on 2023-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0041_alter_worker_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="company",
            field=models.CharField(max_length=80, null=True, verbose_name="Name"),
        ),
    ]
