# Generated by Django 4.2.7 on 2023-12-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0042_services_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workers",
            name="passport",
        ),
        migrations.AddField(
            model_name="workers",
            name="file",
            field=models.FileField(
                null=True, upload_to="static/", verbose_name="Upload CV "
            ),
        ),
    ]
