# Generated by Django 4.2.7 on 2023-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_remove_workers_passport_workers_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=800, null=True, verbose_name="Name"),
                ),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                ("phone", models.CharField(max_length=50, verbose_name="Phone No")),
                (
                    "virtual",
                    models.BooleanField(
                        default=False, null=True, verbose_name="Virtual"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="images/")),
                (
                    "course",
                    models.CharField(max_length=800, null=True, verbose_name="Course"),
                ),
                ("username", models.CharField(max_length=80, null=True)),
                (
                    "firstname",
                    models.CharField(max_length=80, verbose_name="FirstName"),
                ),
                ("lastname", models.CharField(max_length=80, verbose_name="LastName")),
                ("virtual", models.CharField(max_length=80, null=True)),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "experience",
                    models.CharField(
                        max_length=800, null=True, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "duration",
                    models.CharField(max_length=80, null=True, verbose_name="Duration"),
                ),
                (
                    "price",
                    models.CharField(max_length=20, null=True, verbose_name="Price"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="teacher_application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.CharField(max_length=800, null=True, verbose_name="Course"),
                ),
                ("username", models.CharField(max_length=80, null=True)),
                (
                    "firstname",
                    models.CharField(max_length=80, verbose_name="FirstName"),
                ),
                ("lastname", models.CharField(max_length=80, verbose_name="LastName")),
                ("virtual", models.CharField(max_length=80, null=True)),
                ("email", models.CharField(max_length=50, verbose_name="Email")),
                (
                    "experience",
                    models.CharField(
                        max_length=800, null=True, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "duration",
                    models.CharField(max_length=80, null=True, verbose_name="Duration"),
                ),
                (
                    "price",
                    models.CharField(max_length=20, null=True, verbose_name="Price"),
                ),
            ],
        ),
    ]
