# Generated by Django 4.2.7 on 2023-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0044_student_teacher_teacher_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher_application",
            name="phone",
            field=models.CharField(max_length=50, null=True, verbose_name="Phone No"),
        ),
    ]
