# Generated by Django 4.2.7 on 2023-12-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0045_teacher_application_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="virtual",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="teacher_application",
            name="virtual",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
