# Generated by Django 4.2.7 on 2023-12-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0046_alter_teacher_virtual_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="teacher_application",
            new_name="teacherapplication",
        ),
    ]
