# Generated by Django 4.2.7 on 2023-12-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0047_rename_teacher_application_teacherapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherapplication",
            name="virtual",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Virtual or physical class"
            ),
        ),
    ]
