# Generated by Django 4.2.7 on 2024-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0048_alter_teacherapplication_virtual"),
    ]

    operations = [
        migrations.AddField(
            model_name="workercontact",
            name="location",
            field=models.CharField(max_length=800, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="workercontact",
            name="name",
            field=models.CharField(max_length=800, null=True, verbose_name="Fullname"),
        ),
        migrations.AddField(
            model_name="workercontact",
            name="phone",
            field=models.IntegerField(null=True, verbose_name="PhoneNo"),
        ),
        migrations.AlterField(
            model_name="workercontact",
            name="description",
            field=models.TextField(verbose_name="Request"),
        ),
    ]
